#cloud-config
users:
  - name: ubuntu
    ssh_authorized_keys:
      - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKQErZwWAAV+iGF9T/1aaRHyDvIFCqd24glAp6Ws7wm3PKlokxfJ/SUX2GIFsg7Td5WqriTbFop4Y+UMUJMWvQ4= root@versatus.io
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: sudo
    shell: /bin/bash
    passwd: $6$0f4yT5HWBWUwGSJS$UBKG/mob7M9n.SBi/ZYsdo69nTjmA7qua9OMQr/IA/ERXVh21cSMirY7Pu7a3ts8uYxI2FBrH257p6Br1EMvU/
    lock-passwd: false
    chpasswd: { expire: False }
    ssh_pwauth: True
